[ip]
name = "vhdl-examples"
version = "0.1.0"
# uuid = "7754fbdd-6fe3-4683-8949-70fc72b0cefe"
public = ["adder.vhd"]
channels = ["hyperspace-labs"]
exclude = ["fa_tb.vhd"]

# See more keys and their definitions at https://chaseruskin.github.io/orbit/reference/manifest.html

[dependencies]
# serdes = { version = "1.0.0", uuid = "" }