[ip]
name = "vhdl-examples"
version = "0.1.0"
public = ["adder.vhd"]
channels = ["hyperspace-labs"]


# See more keys and their definitions at https://cdotrus.github.io/orbit/reference/manifest.html

[dependencies]
