name: check-release
on:
  workflow_call:
    outputs:
      ready:
        description: 'Auto-release conditional indicator'
        value: ${{ jobs.check-release.outputs.ready }}
      version:
        description: 'Version to release'
        value: ${{ jobs.check-release.outputs.version }}

jobs:
  check-release:
    runs-on: ubuntu-latest
    outputs:
      ready: ${{ steps.ready.outputs.ready }}
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Grab git tags
        run: git fetch --prune --unshallow --tags
        
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Extract Cargo crate version
        id: version
        run: echo "version=$(./tools/evalver.py --version)" >> $GITHUB_OUTPUT

      - name: Evaluate Cargo crate version
        id: ready
        run: echo "ready=$(./tools/evalver.py)" >> $GITHUB_OUTPUT