name: Integrity
on: 
  workflow_call:

jobs:
  integrity:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch Repository
      uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - name: Download artifacts
      uses: actions/download-artifact@v4

    - name: Display filesystem contents
      run: ls -R

    - name: Identify current version
      run: echo "VERSION=$(./tools/evalver.py --version)" >> $GITHUB_ENV

    - name: Compute checksums
      run: echo "$(./tools/sum.py "./**/orbit-*.*")" > ./SHA256SUMS

    - name: Review checksums
      run: cat ./SHA256SUMS

    - name: Upload checksums
      uses: actions/upload-artifact@v4
      with:
        name: SHA256SUMS
        path: ./SHA256SUMS