name: Pipeline
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  tools:
    uses: chaseruskin/orbit/.github/workflows/tools.yml@trunk
    
  check-release:
    uses: chaseruskin/orbit/.github/workflows/check-release.yml@trunk
    needs: [tools]

  build:
    uses: chaseruskin/orbit/.github/workflows/build.yml@trunk
    needs: [check-release]
    with:
      is_release: ${{ needs.check-release.outputs.ready }}

  integrity:
    uses: chaseruskin/orbit/.github/workflows/integrity.yml@trunk
    needs: [tools, build]

  system-test:
    uses: chaseruskin/orbit/.github/workflows/system-test.yml@trunk
    needs: [check-release, integrity]
    with:
      version: ${{ needs.check-release.outputs.version }}

  docker-build:
    uses: chaseruskin/orbit/.github/workflows/docker.yml@trunk
    needs: [check-release, system-test]
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    with:
      version: ${{ needs.check-release.outputs.version }}
      is_release: ${{ needs.check-release.outputs.ready }}

  release:
    uses: chaseruskin/orbit/.github/workflows/release.yml@trunk
    if: ${{ needs.check-release.outputs.ready == '1' }}
    needs: [check-release, system-test, docker-build]
    with:
      version: ${{ needs.check-release.outputs.version }}