name: System Test
on:
  workflow_call:
    inputs:
      version:
        description: 'Version released'
        required: true
        type: string

jobs:
  macos:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Fetch repository
      uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - name: Setup just
      uses: extractions/setup-just@v2

    - name: Download package
      uses: actions/download-artifact@v4
      with:
        name: orbit-${{ inputs.version }}-aarch64-apple-darwin

    - name: Download checksums
      uses: actions/download-artifact@v4
      with:
        name: SHA256SUMS
      
    - name: Download sha256sum binary
      run: brew install coreutils

    - name: Verify contents
      run: grep $(sha256sum orbit-${{ inputs.version }}-aarch64-apple-darwin.tar.gz) SHA256SUMS

    - name: Install Orbit
      run: |
        tar -xf ./orbit-${{ inputs.version }}-aarch64-apple-darwin.tar.gz
        printf '\n\n' | ./install

    - name: Test Orbit
      run: orbit --version

    - name: Run system tests
      run: just run-sys-tests

  ubuntu:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Fetch repository
      uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - name: Setup just
      uses: extractions/setup-just@v2

    - name: Download package
      uses: actions/download-artifact@v4
      with:
        name: orbit-${{ inputs.version }}-x86_64-unknown-linux-musl

    - name: Download checksums
      uses: actions/download-artifact@v4
      with:
        name: SHA256SUMS

    - name: Verify contents
      run: grep $(sha256sum orbit-${{ inputs.version }}-x86_64-unknown-linux-musl.tar.gz) SHA256SUMS

    - name: Install Orbit
      run: |
        tar -xf ./orbit-${{ inputs.version }}-x86_64-unknown-linux-musl.tar.gz
        printf '\n\n' | ./install

    - name: Test Orbit
      run: orbit --version

    - name: Run system tests
      run: just run-sys-tests
    
  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Fetch repository
      uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - name: Setup just
      uses: extractions/setup-just@v2

    - name: Download package
      uses: actions/download-artifact@v4
      with:
        name: orbit-${{ inputs.version }}-x86_64-pc-windows-msvc

    - name: Install Orbit
      run: |
        unzip -o ./orbit-${{ inputs.version }}-x86_64-pc-windows-msvc.zip
        printf 'C:/users/runneradmin\n\n' | ./orbit-${{ inputs.version }}-x86_64-pc-windows-msvc.zip/install.exe 

    - name: Add Orbit to PATH
      run: echo "C:/users/runneradmin/orbit/bin" >> $GITHUB_PATH

    - name: Test Orbit
      run: orbit --version

    - name: Run system tests
      run: just run-sys-tests
